### ISSUE TITLE
fatal error: absl/debugging/leak_check.h: No such file or directory

### ISSUE THREAD

**Issue by welsonzhang** [baidu/babylon#92]
build in Ubunutu22.04 fail:

```
bazel build babylon
```

`
In file included from bazel-out/k8-fastbuild/bin/src/babylon/concurrent/_virtual_includes/thread_local/babylon/concurrent/thread_local.h:3,
                 from bazel-out/k8-fastbuild/bin/src/babylon/concurrent/_virtual_includes/counter/babylon/concurrent/counter.h:3,
                 from src/babylon/concurrent/counter.cpp:1:
bazel-out/k8-fastbuild/bin/src/babylon/_virtual_includes/sanitizer_helper/babylon/sanitizer_helper.h:3:10: fatal error: absl/debugging/leak_check.h: No such file or directory
    3 | #include <absl/debugging/leak_check.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
`

**Comment by welsonzhang** [comment]
https://github.com/baidu/babylon/pull/90/files
